# Build configuration for robot_package
# Generated by RoboDSL

# Build type
set(CMAKE_BUILD_TYPE Release)

# Compiler flags
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG")
set(CMAKE_CXX_FLAGS_DEBUG "-g -O0 -DDEBUG")

# CUDA configuration
set(CMAKE_CUDA_ARCHITECTURES 60 70 75 80 86)
set(CMAKE_CUDA_STANDARD c++17)
set(CMAKE_CUDA_FLAGS_RELEASE "-O3 -DNDEBUG")
set(CMAKE_CUDA_FLAGS_DEBUG "-g -O0 -DDEBUG")

# Testing configuration
set(BUILD_TESTING ON)
set(ENABLE_TESTING ON)

# Documentation
set(BUILD_DOCS ON)

# Install configuration
set(CMAKE_INSTALL_PREFIX "/opt/ros/humble")
