// Generated by RoboDSL - DO NOT EDIT

#ifndef SAFETY_NODE_NODE_HPP
#define SAFETY_NODE_NODE_HPP

// Standard includes
#include <memory>
#include <string>
#include <vector>
#include <map>
#include <cmath>

// ROS2 includes
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <rclcpp_lifecycle/lifecycle_publisher.hpp>
#include <rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp>
#include <rclcpp_action/rclcpp_action.hpp>
// #include <rclcpp_components/register_node_macro.hpp>  // Optional component registration

// CUDA includes (if needed)

// Type definitions
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

// Forward declarations for custom types
struct DetectionResult {
    int id;
    float confidence;
    float x, y, width, height;
};

struct CudaParams {
    int device_id;
    bool enable_processing;
};

// Include geometry_msgs for PoseStamped
#include <geometry_msgs/msg/pose_stamped.hpp>

// Placeholder for missing action types
namespace navigation_msgs { namespace action {
    struct NavigationAction {
        struct Goal {
            geometry_msgs::msg::PoseStamped target_pose;
        };
        struct Result {
            bool success;
        };
        struct Feedback {
            geometry_msgs::msg::PoseStamped current_pose;
        };
    };
}} // namespace navigation_msgs::action

// Alias for convenience
using NavigationAction = navigation_msgs::action::NavigationAction;

// OpenCV forward declarations (minimal)
namespace cv {
    class Mat;
}

// Message includes
#include <std_msgs/msg/bool.hpp>
#include <sensor_msgs/msg/laser_scan.hpp>
#include <geometry_msgs/msg/twist.hpp>


// Global C++ code blocks (passed through as-is)

    // Additional C++ code that gets included in the generated files
    namespace robot_utils {
        // Utility functions
        template<typename T>
        T clamp(T value, T min, T max) {
            return std::max(min, std::min(max, value));
        }
        
        double radians_to_degrees(double radians) {
            return radians * 180.0 / M_PI;
        }
        
        double degrees_to_radians(double degrees) {
            return degrees * M_PI / 180.0;
        }
    }


namespace robodsl {


class Safety_nodeNode : public rclcpp::Node {
public:
    // Referenced global CUDA kernels
    explicit Safety_nodeNode(const rclcpp::NodeOptions& options = rclcpp::NodeOptions());
    ~Safety_nodeNode() override;

    // Lifecycle node interface

    // Timer callbacks
    void on_safety_timer();

    // Subscriber callbacks
    void on_sensor_data(const sensor_msgs::msg::LaserScan::ConstSharedPtr msg);
    void on_cmd_vel(const geometry_msgs::msg::Twist::ConstSharedPtr msg);

    // Service callbacks

    // Action server callbacks

    // CUDA kernels

    // User-defined C++ methods
    /**
     * @brief safety_check - User-defined C++ method
     * @param code Input parameter of type void     */
    void safety_check(
    );

    // Raw C++ code blocks (passed through as-is)

private:
    // ROS2 publishers
    rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr safe_cmd_vel_pub_;
    rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr emergency_stop_pub_;

    // ROS2 subscribers
    rclcpp::Subscription<sensor_msgs::msg::LaserScan>::SharedPtr sensor_data_sub_;
    rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr cmd_vel_sub_;

    // ROS2 services

    // ROS2 action servers

    // ROS2 timers
    rclcpp::TimerBase::SharedPtr safety_timer_timer_;

    // Lifecycle state tracking

    // Additional node state variables
    
    // Message storage for processing

    // Parameters
    double max_acceleration_;
    double emergency_stop_distance_;
    bool enable_emergency_stop_;

    // CUDA members

    // Private methods
    void init_parameters();
    void init_publishers();
    void init_subscribers();
    void init_services();
    void init_action_servers();
    void init_timers();
    void init_cuda();
};

} // namespace robodsl

// Register component
// #include <rclcpp_components/register_node_macro.hpp>  // Optional component registration
RCLCPP_COMPONENTS_REGISTER_NODE(::robodsl::Safety_nodeNode)

#endif // SAFETY_NODE_NODE_HPP
