// Generated by RoboDSL - DO NOT EDIT

#include <cuda_runtime.h>
#include <device_launch_parameters.h>

#include "vector_add_kernel.cuh"
#include <algorithm>
#include <stdexcept>

namespace robodsl {

namespace {

// Device kernel implementation
__global__ void vector_add_kernel(
    float** a,    float** b,    int* size,    float** c, int num_elements
) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    const int stride = blockDim.x * gridDim.x;

    // Process elements in parallel
    for (int i = idx; i < num_elements; i += stride) {
        // Kernel implementation here
        // Example: output[i] = process(input[i], parameters);
    }
}

} // anonymous namespace

vector_addKernel::vector_addKernel(cudaStream_t* stream)
    : stream_(stream) {
    // Initialize CUDA device if needed
    cudaError_t status = cudaGetDevice(&device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get CUDA device: ") + cudaGetErrorString(status);
        return;
    }
    
    // Get device properties
    cudaDeviceProp props;
    status = cudaGetDeviceProperties(&props, device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get device properties: ") + cudaGetErrorString(status);
        return;
    }
    
    // Calculate optimal block size based on device properties
    max_threads_per_block_ = props.maxThreadsPerBlock;
    max_blocks_per_dim_ = props.maxGridSize[0];
    
    // CUDA device initialized successfully
    // Device: %s (Compute %d.%d)
}

vector_addKernel::~vector_addKernel() {
    try {
        freeDeviceMemory();
    } catch (const std::exception& e) {
        // Error in destructor: %s
    }
}

bool vector_addKernel::initialize(const float** input, size_t input_size) {
    if (!input || input_size == 0) {
        last_error_ = "Input pointer is null or size is zero";
        return false;
    }
    
    // Free any previously allocated memory
    freeDeviceMemory();
    
    // Store input size
    input_size_ = input_size;
    
    // Allocate device memory
    if (!allocateDeviceMemory()) {
        return false;
    }
    
    // Copy input data to device
    cudaError_t status = cudaMemcpyAsync(
        d_a_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy a to device")) {
        return false;
    }
    cudaError_t status = cudaMemcpyAsync(
        d_b_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy b to device")) {
        return false;
    }
    cudaError_t status = cudaMemcpyAsync(
        d_size_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy size to device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after initialization")) {
        return false;
    }
    
    initialized_ = true;
    return true;
}

bool vector_addKernel::process(const void* parameters, size_t param_size, float** output, size_t output_size) {
    if (!initialized_) {
        return false;
    }
    
    if (!output || output_size < input_size_) {
        last_error_ = "Output buffer is null or too small";
        return false;
    }
    
    // Copy parameters to device if needed
    
    // Calculate grid and block dimensions
    int block_size = std::min(max_threads_per_block_, kBlockSize);
    int num_blocks = (input_size_ + block_size - 1) / block_size;
    num_blocks = std::min(num_blocks, max_blocks_per_dim_);
    
    // Launch kernel
    vector_add_kernel<<<num_blocks, block_size, 0, stream_ ? *stream_ : 0>>>(
        d_a_,        d_b_,        d_size_,        d_c_, input_size_
    );
    
    // Check for kernel launch errors
    cudaError_t status = cudaGetLastError();
    if (!checkCudaError(status, "Kernel launch")) {
        return false;
    }
    
    // Copy results back to host
    status = cudaMemcpyAsync(
        output, 
        d_c_, 
        input_size_ * sizeof(float*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy c from device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after processing")) {
        return false;
    }
    
    return true;
}

bool vector_addKernel::allocateDeviceMemory() {
    cudaError_t status;
    
    // Allocate memory for all parameters
    status = cudaMalloc(&d_a_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate a memory")) {
        // Free previously allocated memory
        return false;
    }
    status = cudaMalloc(&d_b_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate b memory")) {
        // Free previously allocated memory
        if (d_a_) {
            cudaFree(d_a_);
            d_a_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_size_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate size memory")) {
        // Free previously allocated memory
        if (d_a_) {
            cudaFree(d_a_);
            d_a_ = nullptr;
        }
        if (d_b_) {
            cudaFree(d_b_);
            d_b_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_c_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate c memory")) {
        // Free previously allocated memory
        if (d_a_) {
            cudaFree(d_a_);
            d_a_ = nullptr;
        }
        if (d_b_) {
            cudaFree(d_b_);
            d_b_ = nullptr;
        }
        if (d_size_) {
            cudaFree(d_size_);
            d_size_ = nullptr;
        }
        return false;
    }
    
    return true;
}

void vector_addKernel::freeDeviceMemory() {
    if (d_a_) {
        cudaFree(d_a_);
        d_a_ = nullptr;
    }
    if (d_b_) {
        cudaFree(d_b_);
        d_b_ = nullptr;
    }
    if (d_size_) {
        cudaFree(d_size_);
        d_size_ = nullptr;
    }
    if (d_c_) {
        cudaFree(d_c_);
        d_c_ = nullptr;
    }
    
    input_size_ = 0;
    initialized_ = false;
    parameters_copied_ = false;
}

bool vector_addKernel::checkCudaError(cudaError_t status, const std::string& context) {
    if (status != cudaSuccess) {
        last_error_ = context + ": " + cudaGetErrorString(status);
        return false;
    }
    return true;
}

} // namespace robodsl
