#!/usr/bin/env python3
"""
Launch robot_coordinator node

This file was auto-generated by RoboDSL.
"""

from launch import LaunchDescription
from launch_ros.actions import Node
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration

def generate_launch_description():
    # Declare launch arguments
    launch_arguments = [
        DeclareLaunchArgument(
            'use_sim_time',
            default_value='false',
            description='Use simulation time'
        ),
        DeclareLaunchArgument(
            'log_level',
            default_value='info',
            description='Log level for the node'
        ),
    ]
    
    # Create node
    robot_coordinator_node = Node(
        package='robodsl_package',
        executable='robot_coordinator_node',
        name='robot_coordinator_node',
        namespace='/robot_coordinator',
        output='screen',
        parameters=[
            {'coordination_frequency': 0.0},
            {'inter_robot_safety_distance': 0.0},
            {'use_sim_time': LaunchConfiguration("use_sim_time")},
        ],
        arguments=['--ros-args', '--log-level', LaunchConfiguration('log_level')],
    )

    return LaunchDescription(launch_arguments + [robot_coordinator_node])
