// Generated by RoboDSL - DO NOT EDIT


#include "cuda/safety_monitoring_kernel.cuh"
#include <algorithm>
#include <stdexcept>

// Define uchar type if not already defined
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

namespace robodsl {

namespace {

// Device kernel implementation
__global__ void safety_monitoring_kernel(
    float** vehicle_state,    float** obstacles,    int* num_obstacles,    float** safety_thresholds,    bool** safety_violations,    float** risk_scores, int num_elements
) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    const int stride = blockDim.x * gridDim.x;

    // Process elements in parallel
    for (int i = idx; i < num_elements; i += stride) {
        // Kernel implementation here
        // Example: output[i] = process(input[i], parameters);
    }
}

} // anonymous namespace

safety_monitoringKernel::safety_monitoringKernel(cudaStream_t* stream)
    : stream_(stream) {
    // Initialize CUDA device if needed
    cudaError_t status = cudaGetDevice(&device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get CUDA device: ") + cudaGetErrorString(status);
        return;
    }
    
    // Get device properties
    cudaDeviceProp props;
    status = cudaGetDeviceProperties(&props, device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get device properties: ") + cudaGetErrorString(status);
        return;
    }
    
    // Calculate optimal block size based on device properties
    max_threads_per_block_ = props.maxThreadsPerBlock;
    max_blocks_per_dim_ = props.maxGridSize[0];
    
    // CUDA device initialized successfully
    // Device: %s (Compute %d.%d)
}

safety_monitoringKernel::~safety_monitoringKernel() {
    try {
        freeDeviceMemory();
    } catch (const std::exception& e) {
        // Error in destructor: %s
    }
}

bool safety_monitoringKernel::initialize(const float** input, size_t input_size) {
    if (!input || input_size == 0) {
        last_error_ = "Input pointer is null or size is zero";
        return false;
    }
    
    // Free any previously allocated memory
    freeDeviceMemory();
    
    // Store input size
    input_size_ = input_size;
    
    // Allocate device memory
    if (!allocateDeviceMemory()) {
        return false;
    }
    
    // Declare status variable once
    cudaError_t status;
    
    // Copy input data to device
    status = cudaMemcpyAsync(
        d_vehicle_state_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy vehicle_state to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_obstacles_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy obstacles to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_num_obstacles_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy num_obstacles to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_safety_thresholds_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy safety_thresholds to device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after initialization")) {
        return false;
    }
    
    initialized_ = true;
    return true;
}

bool safety_monitoringKernel::process(const float** parameters, size_t param_size, bool** output, size_t output_size) {
    if (!initialized_) {
        return false;
    }
    
    if (!output || output_size < input_size_) {
        last_error_ = "Output buffer is null or too small";
        return false;
    }
    
    // Declare status variable for this method
    cudaError_t status;
    
    // Copy parameters to device if needed
    if (parameters && !parameters_copied_) {
        status = cudaMemcpyAsync(
            d_parameters_, 
            parameters, 
            param_size, 
            cudaMemcpyHostToDevice,
            stream_ ? *stream_ : 0
        );
        
        if (!checkCudaError(status, "Copy parameters to device")) {
            return false;
        }
        
        parameters_copied_ = true;
    }
    
    // Calculate grid and block dimensions
    int block_size = std::min(max_threads_per_block_, kBlockSize);
    int num_blocks = (input_size_ + block_size - 1) / block_size;
    num_blocks = std::min(num_blocks, max_blocks_per_dim_);
    
    // Launch kernel
    safety_monitoring_kernel<<<num_blocks, block_size, 0, stream_ ? *stream_ : 0>>>(
        d_vehicle_state_,        d_obstacles_,        d_num_obstacles_,        d_safety_thresholds_,        d_safety_violations_,        d_risk_scores_, input_size_
    );
    
    // Check for kernel launch errors
    status = cudaGetLastError();
    if (!checkCudaError(status, "Kernel launch")) {
        return false;
    }
    
    // Copy results back to host
    status = cudaMemcpyAsync(
        output, 
        d_safety_violations_, 
        input_size_ * sizeof(bool*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy safety_violations from device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        output, 
        d_risk_scores_, 
        input_size_ * sizeof(float*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy risk_scores from device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after processing")) {
        return false;
    }
    
    return true;
}

bool safety_monitoringKernel::allocateDeviceMemory() {
    cudaError_t status;
    
    // Allocate memory for all parameters
    status = cudaMalloc(&d_vehicle_state_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate vehicle_state memory")) {
        // Free previously allocated memory
        return false;
    }
    status = cudaMalloc(&d_obstacles_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate obstacles memory")) {
        // Free previously allocated memory
        if (d_vehicle_state_) {
            cudaFree(d_vehicle_state_);
            d_vehicle_state_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_num_obstacles_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate num_obstacles memory")) {
        // Free previously allocated memory
        if (d_vehicle_state_) {
            cudaFree(d_vehicle_state_);
            d_vehicle_state_ = nullptr;
        }
        if (d_obstacles_) {
            cudaFree(d_obstacles_);
            d_obstacles_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_safety_thresholds_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate safety_thresholds memory")) {
        // Free previously allocated memory
        if (d_vehicle_state_) {
            cudaFree(d_vehicle_state_);
            d_vehicle_state_ = nullptr;
        }
        if (d_obstacles_) {
            cudaFree(d_obstacles_);
            d_obstacles_ = nullptr;
        }
        if (d_num_obstacles_) {
            cudaFree(d_num_obstacles_);
            d_num_obstacles_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_safety_violations_, input_size_ * sizeof(bool*));
    if (!checkCudaError(status, "Allocate safety_violations memory")) {
        // Free previously allocated memory
        if (d_vehicle_state_) {
            cudaFree(d_vehicle_state_);
            d_vehicle_state_ = nullptr;
        }
        if (d_obstacles_) {
            cudaFree(d_obstacles_);
            d_obstacles_ = nullptr;
        }
        if (d_num_obstacles_) {
            cudaFree(d_num_obstacles_);
            d_num_obstacles_ = nullptr;
        }
        if (d_safety_thresholds_) {
            cudaFree(d_safety_thresholds_);
            d_safety_thresholds_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_risk_scores_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate risk_scores memory")) {
        // Free previously allocated memory
        if (d_vehicle_state_) {
            cudaFree(d_vehicle_state_);
            d_vehicle_state_ = nullptr;
        }
        if (d_obstacles_) {
            cudaFree(d_obstacles_);
            d_obstacles_ = nullptr;
        }
        if (d_num_obstacles_) {
            cudaFree(d_num_obstacles_);
            d_num_obstacles_ = nullptr;
        }
        if (d_safety_thresholds_) {
            cudaFree(d_safety_thresholds_);
            d_safety_thresholds_ = nullptr;
        }
        if (d_safety_violations_) {
            cudaFree(d_safety_violations_);
            d_safety_violations_ = nullptr;
        }
        return false;
    }
    
    return true;
}

void safety_monitoringKernel::freeDeviceMemory() {
    if (d_vehicle_state_) {
        cudaFree(d_vehicle_state_);
        d_vehicle_state_ = nullptr;
    }
    if (d_obstacles_) {
        cudaFree(d_obstacles_);
        d_obstacles_ = nullptr;
    }
    if (d_num_obstacles_) {
        cudaFree(d_num_obstacles_);
        d_num_obstacles_ = nullptr;
    }
    if (d_safety_thresholds_) {
        cudaFree(d_safety_thresholds_);
        d_safety_thresholds_ = nullptr;
    }
    if (d_safety_violations_) {
        cudaFree(d_safety_violations_);
        d_safety_violations_ = nullptr;
    }
    if (d_risk_scores_) {
        cudaFree(d_risk_scores_);
        d_risk_scores_ = nullptr;
    }
    
    input_size_ = 0;
    initialized_ = false;
    parameters_copied_ = false;
}

bool safety_monitoringKernel::checkCudaError(cudaError_t status, const std::string& context) {
    if (status != cudaSuccess) {
        last_error_ = context + ": " + cudaGetErrorString(status);
        return false;
    }
    return true;
}

} // namespace robodsl
