// Generated by RoboDSL - DO NOT EDIT


#include "cuda/sensor_fusion_kernel.cuh"
#include <algorithm>
#include <stdexcept>

// Define uchar type if not already defined
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

namespace robodsl {

namespace {

// Device kernel implementation
__global__ void sensor_fusion_kernel(
    float** lidar_points,    int* num_lidar_points,    float** camera_detections,    int* num_camera_detections,    float** fused_objects,    int** num_fused_objects, int num_elements
) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    const int stride = blockDim.x * gridDim.x;

    // Process elements in parallel
    for (int i = idx; i < num_elements; i += stride) {
        // Kernel implementation here
        // Example: output[i] = process(input[i], parameters);
    }
}

} // anonymous namespace

sensor_fusionKernel::sensor_fusionKernel(cudaStream_t* stream)
    : stream_(stream) {
    // Initialize CUDA device if needed
    cudaError_t status = cudaGetDevice(&device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get CUDA device: ") + cudaGetErrorString(status);
        return;
    }
    
    // Get device properties
    cudaDeviceProp props;
    status = cudaGetDeviceProperties(&props, device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get device properties: ") + cudaGetErrorString(status);
        return;
    }
    
    // Calculate optimal block size based on device properties
    max_threads_per_block_ = props.maxThreadsPerBlock;
    max_blocks_per_dim_ = props.maxGridSize[0];
    
    // CUDA device initialized successfully
    // Device: %s (Compute %d.%d)
}

sensor_fusionKernel::~sensor_fusionKernel() {
    try {
        freeDeviceMemory();
    } catch (const std::exception& e) {
        // Error in destructor: %s
    }
}

bool sensor_fusionKernel::initialize(const float** input, size_t input_size) {
    if (!input || input_size == 0) {
        last_error_ = "Input pointer is null or size is zero";
        return false;
    }
    
    // Free any previously allocated memory
    freeDeviceMemory();
    
    // Store input size
    input_size_ = input_size;
    
    // Allocate device memory
    if (!allocateDeviceMemory()) {
        return false;
    }
    
    // Declare status variable once
    cudaError_t status;
    
    // Copy input data to device
    status = cudaMemcpyAsync(
        d_lidar_points_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy lidar_points to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_num_lidar_points_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy num_lidar_points to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_camera_detections_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy camera_detections to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_num_camera_detections_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy num_camera_detections to device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after initialization")) {
        return false;
    }
    
    initialized_ = true;
    return true;
}

bool sensor_fusionKernel::process(const int** parameters, size_t param_size, float** output, size_t output_size) {
    if (!initialized_) {
        return false;
    }
    
    if (!output || output_size < input_size_) {
        last_error_ = "Output buffer is null or too small";
        return false;
    }
    
    // Declare status variable for this method
    cudaError_t status;
    
    // Copy parameters to device if needed
    if (parameters && !parameters_copied_) {
        status = cudaMemcpyAsync(
            d_parameters_, 
            parameters, 
            param_size, 
            cudaMemcpyHostToDevice,
            stream_ ? *stream_ : 0
        );
        
        if (!checkCudaError(status, "Copy parameters to device")) {
            return false;
        }
        
        parameters_copied_ = true;
    }
    
    // Calculate grid and block dimensions
    int block_size = std::min(max_threads_per_block_, kBlockSize);
    int num_blocks = (input_size_ + block_size - 1) / block_size;
    num_blocks = std::min(num_blocks, max_blocks_per_dim_);
    
    // Launch kernel
    sensor_fusion_kernel<<<num_blocks, block_size, 0, stream_ ? *stream_ : 0>>>(
        d_lidar_points_,        d_num_lidar_points_,        d_camera_detections_,        d_num_camera_detections_,        d_fused_objects_,        d_num_fused_objects_, input_size_
    );
    
    // Check for kernel launch errors
    status = cudaGetLastError();
    if (!checkCudaError(status, "Kernel launch")) {
        return false;
    }
    
    // Copy results back to host
    status = cudaMemcpyAsync(
        output, 
        d_fused_objects_, 
        input_size_ * sizeof(float*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy fused_objects from device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        output, 
        d_num_fused_objects_, 
        input_size_ * sizeof(int*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy num_fused_objects from device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after processing")) {
        return false;
    }
    
    return true;
}

bool sensor_fusionKernel::allocateDeviceMemory() {
    cudaError_t status;
    
    // Allocate memory for all parameters
    status = cudaMalloc(&d_lidar_points_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate lidar_points memory")) {
        // Free previously allocated memory
        return false;
    }
    status = cudaMalloc(&d_num_lidar_points_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate num_lidar_points memory")) {
        // Free previously allocated memory
        if (d_lidar_points_) {
            cudaFree(d_lidar_points_);
            d_lidar_points_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_camera_detections_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate camera_detections memory")) {
        // Free previously allocated memory
        if (d_lidar_points_) {
            cudaFree(d_lidar_points_);
            d_lidar_points_ = nullptr;
        }
        if (d_num_lidar_points_) {
            cudaFree(d_num_lidar_points_);
            d_num_lidar_points_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_num_camera_detections_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate num_camera_detections memory")) {
        // Free previously allocated memory
        if (d_lidar_points_) {
            cudaFree(d_lidar_points_);
            d_lidar_points_ = nullptr;
        }
        if (d_num_lidar_points_) {
            cudaFree(d_num_lidar_points_);
            d_num_lidar_points_ = nullptr;
        }
        if (d_camera_detections_) {
            cudaFree(d_camera_detections_);
            d_camera_detections_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_fused_objects_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate fused_objects memory")) {
        // Free previously allocated memory
        if (d_lidar_points_) {
            cudaFree(d_lidar_points_);
            d_lidar_points_ = nullptr;
        }
        if (d_num_lidar_points_) {
            cudaFree(d_num_lidar_points_);
            d_num_lidar_points_ = nullptr;
        }
        if (d_camera_detections_) {
            cudaFree(d_camera_detections_);
            d_camera_detections_ = nullptr;
        }
        if (d_num_camera_detections_) {
            cudaFree(d_num_camera_detections_);
            d_num_camera_detections_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_num_fused_objects_, input_size_ * sizeof(int*));
    if (!checkCudaError(status, "Allocate num_fused_objects memory")) {
        // Free previously allocated memory
        if (d_lidar_points_) {
            cudaFree(d_lidar_points_);
            d_lidar_points_ = nullptr;
        }
        if (d_num_lidar_points_) {
            cudaFree(d_num_lidar_points_);
            d_num_lidar_points_ = nullptr;
        }
        if (d_camera_detections_) {
            cudaFree(d_camera_detections_);
            d_camera_detections_ = nullptr;
        }
        if (d_num_camera_detections_) {
            cudaFree(d_num_camera_detections_);
            d_num_camera_detections_ = nullptr;
        }
        if (d_fused_objects_) {
            cudaFree(d_fused_objects_);
            d_fused_objects_ = nullptr;
        }
        return false;
    }
    
    return true;
}

void sensor_fusionKernel::freeDeviceMemory() {
    if (d_lidar_points_) {
        cudaFree(d_lidar_points_);
        d_lidar_points_ = nullptr;
    }
    if (d_num_lidar_points_) {
        cudaFree(d_num_lidar_points_);
        d_num_lidar_points_ = nullptr;
    }
    if (d_camera_detections_) {
        cudaFree(d_camera_detections_);
        d_camera_detections_ = nullptr;
    }
    if (d_num_camera_detections_) {
        cudaFree(d_num_camera_detections_);
        d_num_camera_detections_ = nullptr;
    }
    if (d_fused_objects_) {
        cudaFree(d_fused_objects_);
        d_fused_objects_ = nullptr;
    }
    if (d_num_fused_objects_) {
        cudaFree(d_num_fused_objects_);
        d_num_fused_objects_ = nullptr;
    }
    
    input_size_ = 0;
    initialized_ = false;
    parameters_copied_ = false;
}

bool sensor_fusionKernel::checkCudaError(cudaError_t status, const std::string& context) {
    if (status != cudaSuccess) {
        last_error_ = context + ": " + cudaGetErrorString(status);
        return false;
    }
    return true;
}

} // namespace robodsl
