// Generated by RoboDSL - DO NOT EDIT

#ifndef NAVIGATION_NODE_NODE_HPP
#define NAVIGATION_NODE_NODE_HPP

// Standard includes
#include <memory>
#include <string>
#include <vector>

// ROS2 includes
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <rclcpp_lifecycle/lifecycle_publisher.hpp>
#include <rclcpp_lifecycle/lifecycle_node_interface.hpp>
#include <rclcpp_components/register_node_macro.hpp>

// Message includes
#include <geometry_msgs/msg/PoseStamped.hpp>
#include <NavigationAction.hpp>
#include <nav_msgs/msg/Path.hpp>
#include <geometry_msgs/msg/Twist.hpp>


// Global C++ code blocks (passed through as-is)

    // Additional C++ code that gets included in the generated files
    namespace robot_utils {
        // Utility functions
        template<typename T>
        T clamp(T value, T min, T max) {
            return std::max(min, std::min(max, value));
        }
        
        double radians_to_degrees(double radians) {
            return radians * 180.0 / M_PI;
        }
        
        double degrees_to_radians(double degrees) {
            return degrees * M_PI / 180.0;
        }
    }


namespace robodsl {


class Navigation_nodeNode : public rclcpp::Node {
public:
    // Referenced global CUDA kernels
    explicit Navigation_nodeNode(const rclcpp::NodeOptions& options = rclcpp::NodeOptions());
    ~Navigation_nodeNode() override;

    // Lifecycle node interface

    // Timer callbacks
    void on_navigation_timer();

    // Subscriber callbacks
    void on_goal_pose(const geometry_msgs::msg::PoseStamped::ConstSharedPtr msg);

    // Service callbacks

    // Action server callbacks
    rclcpp_action::GoalResponse handle_/navigate_to_pose_goal(
        const rclcpp_action::GoalUUID& uuid,
        std::shared_ptr<const NavigationAction::Goal> goal);
        
    rclcpp_action::CancelResponse handle_/navigate_to_pose_cancel(
        const std::shared_ptr<rclcpp_action::ServerGoalHandle<NavigationAction>> goal_handle);
        
    void handle_/navigate_to_pose_accepted(
        const std::shared_ptr<rclcpp_action::ServerGoalHandle<NavigationAction>> goal_handle);
    
    void execute_/navigate_to_pose(
        const std::shared_ptr<rclcpp_action::ServerGoalHandle<NavigationAction>> goal_handle);

    // CUDA kernels

    // User-defined C++ methods
    /**
     * @brief navigation_step - User-defined C++ method
     * @param code Input parameter of type void     */
    void navigation_step(
void code    );

    // Raw C++ code blocks (passed through as-is)

private:
    // ROS2 publishers
    rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr cmd_vel_pub_;
    rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr path_pub_;

    // ROS2 subscribers
    rclcpp::Subscription<geometry_msgs::msg::PoseStamped>::SharedPtr goal_pose_sub_;

    // ROS2 services

    // ROS2 action servers
    rclcpp_action::Server<NavigationAction>::SharedPtr /navigate_to_pose_action_server_;

    // ROS2 timers
    rclcpp::TimerBase::SharedPtr navigation_timer_timer_;

    // Parameters
    float max_velocity_;
    float goal_tolerance_;
    bool enable_obstacle_avoidance_;

    // CUDA members

    // Private methods
    void init_parameters();
    void init_publishers();
    void init_subscribers();
    void init_services();
    void init_action_servers();
    void init_timers();
    void init_cuda();
};

} // namespace robodsl

// Register component
#include <rclcpp_components/register_node_macro.hpp>
RCLCPP_COMPONENTS_REGISTER_NODE(::robodsl::Navigation_nodeNode)

#endif // NAVIGATION_NODE_NODE_HPP
