// Generated by RoboDSL - DO NOT EDIT

#ifndef CAMERA_SYNCHRONIZER_NODE_HPP
#define CAMERA_SYNCHRONIZER_NODE_HPP

// Standard includes
#include <memory>
#include <string>
#include <vector>
#include <map>
#include <cmath>
#include <functional>
#include <thread>
#include <atomic>

// ROS2 includes
#include <rclcpp/rclcpp.hpp>

// Message includes
#include <sensor_msgs/msg/image.hpp>

// Additional ROS2 includes

// CUDA includes (if needed)

// OpenCV includes (if needed)

// Type definitions
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

// Forward declarations for custom types

// CUDA parameter structs


class Camera_synchronizerNode : public rclcpp::Node {
public:
    explicit Camera_synchronizerNode(const rclcpp::NodeOptions& options = rclcpp::NodeOptions());
    virtual ~Camera_synchronizerNode();


    // Timer callbacks

    // Subscriber callbacks
    void on_camera_image_raw(const sensor_msgs::msg::Image::ConstSharedPtr msg);
    void on_camera2_image_raw(const sensor_msgs::msg::Image::ConstSharedPtr msg);
    void on_camera3_image_raw(const sensor_msgs::msg::Image::ConstSharedPtr msg);

    // Service callbacks



    // User-defined C++ methods

private:
    // Publishers
    std::shared_ptr<rclcpp::Publisher<sensor_msgs::msg::Image>> synchronized_camera1_pub_;
    std::shared_ptr<rclcpp::Publisher<sensor_msgs::msg::Image>> synchronized_camera2_pub_;
    std::shared_ptr<rclcpp::Publisher<sensor_msgs::msg::Image>> synchronized_camera3_pub_;

    // Subscribers
    rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr camera_image_raw_sub_;
    rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr camera2_image_raw_sub_;
    rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr camera3_image_raw_sub_;

    // Services


    // Timers

    // Lifecycle state tracking

    
    // Processing control
    bool enable_processing_{true};

    // Parameters
    double sync_tolerance_;
    int max_queue_size_;

    // Latest message storage (per-subscriber)
    sensor_msgs::msg::Image::ConstSharedPtr latest_camera_image_raw_;
    sensor_msgs::msg::Image::ConstSharedPtr latest_camera2_image_raw_;
    sensor_msgs::msg::Image::ConstSharedPtr latest_camera3_image_raw_;

    // CUDA kernel member variables

    // Helper methods
    void init_parameters();
    void init_publishers();
    void init_subscribers();
    void init_services();
    void init_timers();
};


#endif // CAMERA_SYNCHRONIZER_NODE_HPP
