// Generated by RoboDSL - DO NOT EDIT

#ifndef PERCEPTION_NODE_NODE_HPP
#define PERCEPTION_NODE_NODE_HPP

// Standard includes
#include <memory>
#include <string>
#include <vector>
#include <map>
#include <cmath>
#include <functional>
#include <thread>
#include <atomic>

// ROS2 includes
#include <rclcpp/rclcpp.hpp>

// Message includes
#include <sensor_msgs/msg/image.hpp>
#include <std_msgs/msg/string.hpp>

// Additional ROS2 includes

// CUDA includes (if needed)

// OpenCV includes (if needed)

// Type definitions
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

// Forward declarations for custom types

// CUDA parameter structs

namespace perception {

class Perception_nodeNode : public rclcpp::Node {
public:
    explicit Perception_nodeNode(const rclcpp::NodeOptions& options = rclcpp::NodeOptions());
    virtual ~Perception_nodeNode();


    // Timer callbacks
    void on_processing_timer();

    // Subscriber callbacks
    void on_image_raw(const sensor_msgs::msg::Image::ConstSharedPtr msg);

    // Service callbacks



    // User-defined C++ methods

private:
    // Publishers
    std::shared_ptr<rclcpp::Publisher<std_msgs::msg::String>> detections_pub_;
    std::shared_ptr<rclcpp::Publisher<sensor_msgs::msg::Image>> segmentation_pub_;

    // Subscribers
    rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image_raw_sub_;

    // Services


    // Timers
    rclcpp::TimerBase::SharedPtr processing_timer_timer_;

    // Lifecycle state tracking

    
    // Processing control
    bool enable_processing_{true};

    // Parameters
    bool enable_gpu_;
    // Parameter confidence_threshold of type float not supported in member variables
    // Parameter model_path of type string not supported in member variables

    // Latest message storage
    sensor_msgs::msg::Image::ConstSharedPtr latest_image_;

    // CUDA kernel member variables

    // Helper methods
    void init_parameters();
    void init_publishers();
    void init_subscribers();
    void init_services();
    void init_timers();
};

} // namespace perception

#endif // PERCEPTION_NODE_NODE_HPP
