// Generated by RoboDSL - DO NOT EDIT


#include "cuda/collision_detection_kernel.cuh"
#include <algorithm>
#include <stdexcept>

// Define uchar type if not already defined
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

namespace robodsl {

namespace {

// Device kernel implementation
__global__ void collision_detection_kernel(
    float** robot_joints,    float** robot_geometry,    float** obstacle_points,    int* num_obstacles,    bool** collision_detected, int num_elements
) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    const int stride = blockDim.x * gridDim.x;

    // Process elements in parallel
    for (int i = idx; i < num_elements; i += stride) {
        // Kernel implementation here
        // Example: output[i] = process(input[i], parameters);
    }
}

} // anonymous namespace

collision_detectionKernel::collision_detectionKernel(cudaStream_t* stream)
    : stream_(stream) {
    // Initialize CUDA device if needed
    cudaError_t status = cudaGetDevice(&device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get CUDA device: ") + cudaGetErrorString(status);
        return;
    }
    
    // Get device properties
    cudaDeviceProp props;
    status = cudaGetDeviceProperties(&props, device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get device properties: ") + cudaGetErrorString(status);
        return;
    }
    
    // Calculate optimal block size based on device properties
    max_threads_per_block_ = props.maxThreadsPerBlock;
    max_blocks_per_dim_ = props.maxGridSize[0];
    
    // CUDA device initialized successfully
    // Device: %s (Compute %d.%d)
}

collision_detectionKernel::~collision_detectionKernel() {
    try {
        freeDeviceMemory();
    } catch (const std::exception& e) {
        // Error in destructor: %s
    }
}

bool collision_detectionKernel::initialize(const float** input, size_t input_size) {
    if (!input || input_size == 0) {
        last_error_ = "Input pointer is null or size is zero";
        return false;
    }
    
    // Free any previously allocated memory
    freeDeviceMemory();
    
    // Store input size
    input_size_ = input_size;
    
    // Allocate device memory
    if (!allocateDeviceMemory()) {
        return false;
    }
    
    // Declare status variable once
    cudaError_t status;
    
    // Copy input data to device
    status = cudaMemcpyAsync(
        d_robot_joints_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy robot_joints to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_robot_geometry_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy robot_geometry to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_obstacle_points_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy obstacle_points to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_num_obstacles_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy num_obstacles to device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after initialization")) {
        return false;
    }
    
    initialized_ = true;
    return true;
}

bool collision_detectionKernel::process(const bool** parameters, size_t param_size, bool** output, size_t output_size) {
    if (!initialized_) {
        return false;
    }
    
    if (!output || output_size < input_size_) {
        last_error_ = "Output buffer is null or too small";
        return false;
    }
    
    // Declare status variable for this method
    cudaError_t status;
    
    // Copy parameters to device if needed
    if (parameters && !parameters_copied_) {
        status = cudaMemcpyAsync(
            d_parameters_, 
            parameters, 
            param_size, 
            cudaMemcpyHostToDevice,
            stream_ ? *stream_ : 0
        );
        
        if (!checkCudaError(status, "Copy parameters to device")) {
            return false;
        }
        
        parameters_copied_ = true;
    }
    
    // Calculate grid and block dimensions
    int block_size = std::min(max_threads_per_block_, kBlockSize);
    int num_blocks = (input_size_ + block_size - 1) / block_size;
    num_blocks = std::min(num_blocks, max_blocks_per_dim_);
    
    // Launch kernel
    collision_detection_kernel<<<num_blocks, block_size, 0, stream_ ? *stream_ : 0>>>(
        d_robot_joints_,        d_robot_geometry_,        d_obstacle_points_,        d_num_obstacles_,        d_collision_detected_, input_size_
    );
    
    // Check for kernel launch errors
    status = cudaGetLastError();
    if (!checkCudaError(status, "Kernel launch")) {
        return false;
    }
    
    // Copy results back to host
    status = cudaMemcpyAsync(
        output, 
        d_collision_detected_, 
        input_size_ * sizeof(bool*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy collision_detected from device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after processing")) {
        return false;
    }
    
    return true;
}

bool collision_detectionKernel::allocateDeviceMemory() {
    cudaError_t status;
    
    // Allocate memory for all parameters
    status = cudaMalloc(&d_robot_joints_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate robot_joints memory")) {
        // Free previously allocated memory
        return false;
    }
    status = cudaMalloc(&d_robot_geometry_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate robot_geometry memory")) {
        // Free previously allocated memory
        if (d_robot_joints_) {
            cudaFree(d_robot_joints_);
            d_robot_joints_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_obstacle_points_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate obstacle_points memory")) {
        // Free previously allocated memory
        if (d_robot_joints_) {
            cudaFree(d_robot_joints_);
            d_robot_joints_ = nullptr;
        }
        if (d_robot_geometry_) {
            cudaFree(d_robot_geometry_);
            d_robot_geometry_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_num_obstacles_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate num_obstacles memory")) {
        // Free previously allocated memory
        if (d_robot_joints_) {
            cudaFree(d_robot_joints_);
            d_robot_joints_ = nullptr;
        }
        if (d_robot_geometry_) {
            cudaFree(d_robot_geometry_);
            d_robot_geometry_ = nullptr;
        }
        if (d_obstacle_points_) {
            cudaFree(d_obstacle_points_);
            d_obstacle_points_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_collision_detected_, input_size_ * sizeof(bool*));
    if (!checkCudaError(status, "Allocate collision_detected memory")) {
        // Free previously allocated memory
        if (d_robot_joints_) {
            cudaFree(d_robot_joints_);
            d_robot_joints_ = nullptr;
        }
        if (d_robot_geometry_) {
            cudaFree(d_robot_geometry_);
            d_robot_geometry_ = nullptr;
        }
        if (d_obstacle_points_) {
            cudaFree(d_obstacle_points_);
            d_obstacle_points_ = nullptr;
        }
        if (d_num_obstacles_) {
            cudaFree(d_num_obstacles_);
            d_num_obstacles_ = nullptr;
        }
        return false;
    }
    
    return true;
}

void collision_detectionKernel::freeDeviceMemory() {
    if (d_robot_joints_) {
        cudaFree(d_robot_joints_);
        d_robot_joints_ = nullptr;
    }
    if (d_robot_geometry_) {
        cudaFree(d_robot_geometry_);
        d_robot_geometry_ = nullptr;
    }
    if (d_obstacle_points_) {
        cudaFree(d_obstacle_points_);
        d_obstacle_points_ = nullptr;
    }
    if (d_num_obstacles_) {
        cudaFree(d_num_obstacles_);
        d_num_obstacles_ = nullptr;
    }
    if (d_collision_detected_) {
        cudaFree(d_collision_detected_);
        d_collision_detected_ = nullptr;
    }
    
    input_size_ = 0;
    initialized_ = false;
    parameters_copied_ = false;
}

bool collision_detectionKernel::checkCudaError(cudaError_t status, const std::string& context) {
    if (status != cudaSuccess) {
        last_error_ = context + ": " + cudaGetErrorString(status);
        return false;
    }
    return true;
}

} // namespace robodsl
