// Generated by RoboDSL - DO NOT EDIT


#include "cuda/force_control_kernel.cuh"
#include <algorithm>
#include <stdexcept>

// Define uchar type if not already defined
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

namespace robodsl {

namespace {

// Device kernel implementation
__global__ void force_control_kernel(
    float** desired_force,    float** measured_force,    float** current_pose,    float** stiffness_matrix,    float** force_correction, int num_elements
) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    const int stride = blockDim.x * gridDim.x;

    // Process elements in parallel
    for (int i = idx; i < num_elements; i += stride) {
        // Kernel implementation here
        // Example: output[i] = process(input[i], parameters);
    }
}

} // anonymous namespace

force_controlKernel::force_controlKernel(cudaStream_t* stream)
    : stream_(stream) {
    // Initialize CUDA device if needed
    cudaError_t status = cudaGetDevice(&device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get CUDA device: ") + cudaGetErrorString(status);
        return;
    }
    
    // Get device properties
    cudaDeviceProp props;
    status = cudaGetDeviceProperties(&props, device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get device properties: ") + cudaGetErrorString(status);
        return;
    }
    
    // Calculate optimal block size based on device properties
    max_threads_per_block_ = props.maxThreadsPerBlock;
    max_blocks_per_dim_ = props.maxGridSize[0];
    
    // CUDA device initialized successfully
    // Device: %s (Compute %d.%d)
}

force_controlKernel::~force_controlKernel() {
    try {
        freeDeviceMemory();
    } catch (const std::exception& e) {
        // Error in destructor: %s
    }
}

bool force_controlKernel::initialize(const float** input, size_t input_size) {
    if (!input || input_size == 0) {
        last_error_ = "Input pointer is null or size is zero";
        return false;
    }
    
    // Free any previously allocated memory
    freeDeviceMemory();
    
    // Store input size
    input_size_ = input_size;
    
    // Allocate device memory
    if (!allocateDeviceMemory()) {
        return false;
    }
    
    // Declare status variable once
    cudaError_t status;
    
    // Copy input data to device
    status = cudaMemcpyAsync(
        d_desired_force_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy desired_force to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_measured_force_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy measured_force to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_current_pose_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy current_pose to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_stiffness_matrix_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy stiffness_matrix to device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after initialization")) {
        return false;
    }
    
    initialized_ = true;
    return true;
}

bool force_controlKernel::process(const float** parameters, size_t param_size, float** output, size_t output_size) {
    if (!initialized_) {
        return false;
    }
    
    if (!output || output_size < input_size_) {
        last_error_ = "Output buffer is null or too small";
        return false;
    }
    
    // Declare status variable for this method
    cudaError_t status;
    
    // Copy parameters to device if needed
    if (parameters && !parameters_copied_) {
        status = cudaMemcpyAsync(
            d_parameters_, 
            parameters, 
            param_size, 
            cudaMemcpyHostToDevice,
            stream_ ? *stream_ : 0
        );
        
        if (!checkCudaError(status, "Copy parameters to device")) {
            return false;
        }
        
        parameters_copied_ = true;
    }
    
    // Calculate grid and block dimensions
    int block_size = std::min(max_threads_per_block_, kBlockSize);
    int num_blocks = (input_size_ + block_size - 1) / block_size;
    num_blocks = std::min(num_blocks, max_blocks_per_dim_);
    
    // Launch kernel
    force_control_kernel<<<num_blocks, block_size, 0, stream_ ? *stream_ : 0>>>(
        d_desired_force_,        d_measured_force_,        d_current_pose_,        d_stiffness_matrix_,        d_force_correction_, input_size_
    );
    
    // Check for kernel launch errors
    status = cudaGetLastError();
    if (!checkCudaError(status, "Kernel launch")) {
        return false;
    }
    
    // Copy results back to host
    status = cudaMemcpyAsync(
        output, 
        d_force_correction_, 
        input_size_ * sizeof(float*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy force_correction from device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after processing")) {
        return false;
    }
    
    return true;
}

bool force_controlKernel::allocateDeviceMemory() {
    cudaError_t status;
    
    // Allocate memory for all parameters
    status = cudaMalloc(&d_desired_force_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate desired_force memory")) {
        // Free previously allocated memory
        return false;
    }
    status = cudaMalloc(&d_measured_force_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate measured_force memory")) {
        // Free previously allocated memory
        if (d_desired_force_) {
            cudaFree(d_desired_force_);
            d_desired_force_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_current_pose_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate current_pose memory")) {
        // Free previously allocated memory
        if (d_desired_force_) {
            cudaFree(d_desired_force_);
            d_desired_force_ = nullptr;
        }
        if (d_measured_force_) {
            cudaFree(d_measured_force_);
            d_measured_force_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_stiffness_matrix_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate stiffness_matrix memory")) {
        // Free previously allocated memory
        if (d_desired_force_) {
            cudaFree(d_desired_force_);
            d_desired_force_ = nullptr;
        }
        if (d_measured_force_) {
            cudaFree(d_measured_force_);
            d_measured_force_ = nullptr;
        }
        if (d_current_pose_) {
            cudaFree(d_current_pose_);
            d_current_pose_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_force_correction_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate force_correction memory")) {
        // Free previously allocated memory
        if (d_desired_force_) {
            cudaFree(d_desired_force_);
            d_desired_force_ = nullptr;
        }
        if (d_measured_force_) {
            cudaFree(d_measured_force_);
            d_measured_force_ = nullptr;
        }
        if (d_current_pose_) {
            cudaFree(d_current_pose_);
            d_current_pose_ = nullptr;
        }
        if (d_stiffness_matrix_) {
            cudaFree(d_stiffness_matrix_);
            d_stiffness_matrix_ = nullptr;
        }
        return false;
    }
    
    return true;
}

void force_controlKernel::freeDeviceMemory() {
    if (d_desired_force_) {
        cudaFree(d_desired_force_);
        d_desired_force_ = nullptr;
    }
    if (d_measured_force_) {
        cudaFree(d_measured_force_);
        d_measured_force_ = nullptr;
    }
    if (d_current_pose_) {
        cudaFree(d_current_pose_);
        d_current_pose_ = nullptr;
    }
    if (d_stiffness_matrix_) {
        cudaFree(d_stiffness_matrix_);
        d_stiffness_matrix_ = nullptr;
    }
    if (d_force_correction_) {
        cudaFree(d_force_correction_);
        d_force_correction_ = nullptr;
    }
    
    input_size_ = 0;
    initialized_ = false;
    parameters_copied_ = false;
}

bool force_controlKernel::checkCudaError(cudaError_t status, const std::string& context) {
    if (status != cudaSuccess) {
        last_error_ = context + ": " + cudaGetErrorString(status);
        return false;
    }
    return true;
}

} // namespace robodsl
