#!/usr/bin/env python3
"""
Launch autonomous_navigator node

This file was auto-generated by RoboDSL.
"""

from launch import LaunchDescription
from launch_ros.actions import Node
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration

def generate_launch_description():
    # Declare launch arguments
    launch_arguments = [
        DeclareLaunchArgument(
            'use_sim_time',
            default_value='false',
            description='Use simulation time'
        ),
        DeclareLaunchArgument(
            'log_level',
            default_value='info',
            description='Log level for the node'
        ),
    ]
    
    # Create node
    autonomous_navigator_node = Node(
        package='robodsl_package',
        executable='autonomous_navigator_node',
        name='autonomous_navigator_node',
        namespace='/autonomous_navigator',
        output='screen',
        parameters=[
            {'map_resolution': 0.0},
            {'map_width': 0},
            {'map_height': 0},
            {'min_point_distance': 0.0},
            {'max_point_distance': 0.0},
            {'yolo_model_path': ""},
            {'semantic_model_path': ""},
            {'confidence_threshold': 0.0},
            {'max_linear_velocity': 0.0},
            {'max_angular_velocity': 0.0},
            {'path_planning_frequency': 0.0},
            {'slam_update_frequency': 0.0},
            {'use_sim_time': LaunchConfiguration("use_sim_time")},
        ],
        arguments=['--ros-args', '--log-level', LaunchConfiguration('log_level')],
    )

    return LaunchDescription(launch_arguments + [autonomous_navigator_node])
