// Generated by RoboDSL - DO NOT EDIT

#include "neural_network_kernel_kernel.cuh"
#include <algorithm>
#include <stdexcept>

namespace robodsl {

namespace {

// Device kernel implementation
__global__ void neural_network_kernel_kernel(
    float* input_data,    float* weights,    int input_size,    float* output_data,    int output_size) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    const int stride = blockDim.x * gridDim.x;

    // Process elements in parallel
    for (int i = idx; i < num_elements; i += stride) {
        // Kernel implementation here
        // Example: output[i] = process(input[i], parameters);
    }
}

} // anonymous namespace

neural_network_kernelKernel::neural_network_kernelKernel(cudaStream_t* stream)
    : stream_(stream) {
    // Initialize CUDA device if needed
    cudaError_t status = cudaGetDevice(&device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get CUDA device: ") + cudaGetErrorString(status);
        return;
    }
    
    // Get device properties
    cudaDeviceProp props;
    status = cudaGetDeviceProperties(&props, device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get device properties: ") + cudaGetErrorString(status);
        return;
    }
    
    // Calculate optimal block size based on device properties
    max_threads_per_block_ = props.maxThreadsPerBlock;
    max_blocks_per_dim_ = props.maxGridSize[0];
    
    RCLCPP_DEBUG(rclcpp::get_logger("neural_network_kernelKernel"), 
                "Initialized CUDA device: %s (Compute %d.%d)", 
                props.name, props.major, props.minor);
}

neural_network_kernelKernel::~neural_network_kernelKernel() {
    try {
        freeDeviceMemory();
    } catch (const std::exception& e) {
        RCLCPP_ERROR(rclcpp::get_logger("neural_network_kernelKernel"), 
                    "Error in destructor: %s", e.what());
    }
}

bool neural_network_kernelKernel::initialize(const std::vector<float*>& input) {
    if (input.empty()) {
        last_error_ = "Input vector is empty";
        return false;
    }
    
    // Free any previously allocated memory
    freeDeviceMemory();
    
    // Store input size
    input_size_ = input.size();
    
    // Allocate device memory
    if (!allocateDeviceMemory()) {
        return false;
    }
    
    // Copy input data to device
    cudaError_t status = cudaMemcpyAsync(
        d_input_data_, 
        input.data(), 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy input_data to device")) {
        return false;
    }
    cudaError_t status = cudaMemcpyAsync(
        d_weights_, 
        input.data(), 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy weights to device")) {
        return false;
    }
    cudaError_t status = cudaMemcpyAsync(
        d_input_size_, 
        input.data(), 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy input_size to device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after initialization")) {
        return false;
    }
    
    initialized_ = true;
    return true;
}

std::vector<float*> neural_network_kernelKernel::process(const KernelParameters& parameters) {
    if (!initialized_) {
        throw std::runtime_error("Kernel not initialized");
    }
    
    // Copy parameters to device if needed
    if (!parameters_copied_ || parameters != last_parameters_) {
        cudaError_t status = cudaMemcpyAsync(
            d_parameters_, 
            &parameters, 
            sizeof(KernelParameters), 
            cudaMemcpyHostToDevice,
            stream_ ? *stream_ : 0
        );
        
        if (!checkCudaError(status, "Copy parameters to device")) {
            throw std::runtime_error("Failed to copy parameters to device: " + last_error_);
        }
        
        last_parameters_ = parameters;
        parameters_copied_ = true;
    }
    
    // Calculate grid and block dimensions
    int block_size = std::min(max_threads_per_block_, kBlockSize);
    int num_blocks = (input_size_ + block_size - 1) / block_size;
    num_blocks = std::min(num_blocks, max_blocks_per_dim_);
    
    // Launch kernel
    neural_network_kernel_kernel<<<num_blocks, block_size, 0, stream_ ? *stream_ : 0>>>(
        d_input_data_,        d_weights_,        d_input_size_,        d_output_data_,        d_output_size_    );
    
    // Check for kernel launch errors
    cudaError_t status = cudaGetLastError();
    if (!checkCudaError(status, "Kernel launch")) {
        throw std::runtime_error("Kernel launch failed: " + last_error_);
    }
    
    // Allocate output vector
    std::vector<float*> output(input_size_);
    
    // Copy results back to host
    status = cudaMemcpyAsync(
        output.data(), 
        d_output_data_, 
        input_size_ * sizeof(float*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy output_data from device")) {
        throw std::runtime_error("Failed to copy output_data from device: " + last_error_);
    }
    status = cudaMemcpyAsync(
        output.data(), 
        d_output_size_, 
        input_size_ * sizeof(int), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy output_size from device")) {
        throw std::runtime_error("Failed to copy output_size from device: " + last_error_);
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after processing")) {
        throw std::runtime_error("Synchronization failed: " + last_error_);
    }
    
    return output;
}

bool neural_network_kernelKernel::allocateDeviceMemory() {
    cudaError_t status;
    
    // Allocate memory for all parameters
    status = cudaMalloc(&d_input_data_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate input_data memory")) {
        // Free previously allocated memory
        return false;
    }
    status = cudaMalloc(&d_weights_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate weights memory")) {
        // Free previously allocated memory
        if (d_input_data_) {
            cudaFree(d_input_data_);
            d_input_data_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_input_size_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate input_size memory")) {
        // Free previously allocated memory
        if (d_input_data_) {
            cudaFree(d_input_data_);
            d_input_data_ = nullptr;
        }
        if (d_weights_) {
            cudaFree(d_weights_);
            d_weights_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_output_data_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate output_data memory")) {
        // Free previously allocated memory
        if (d_input_data_) {
            cudaFree(d_input_data_);
            d_input_data_ = nullptr;
        }
        if (d_weights_) {
            cudaFree(d_weights_);
            d_weights_ = nullptr;
        }
        if (d_input_size_) {
            cudaFree(d_input_size_);
            d_input_size_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_output_size_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate output_size memory")) {
        // Free previously allocated memory
        if (d_input_data_) {
            cudaFree(d_input_data_);
            d_input_data_ = nullptr;
        }
        if (d_weights_) {
            cudaFree(d_weights_);
            d_weights_ = nullptr;
        }
        if (d_input_size_) {
            cudaFree(d_input_size_);
            d_input_size_ = nullptr;
        }
        if (d_output_data_) {
            cudaFree(d_output_data_);
            d_output_data_ = nullptr;
        }
        return false;
    }
    
    return true;
}

void neural_network_kernelKernel::freeDeviceMemory() {
    if (d_input_data_) {
        cudaFree(d_input_data_);
        d_input_data_ = nullptr;
    }
    if (d_weights_) {
        cudaFree(d_weights_);
        d_weights_ = nullptr;
    }
    if (d_input_size_) {
        cudaFree(d_input_size_);
        d_input_size_ = nullptr;
    }
    if (d_output_data_) {
        cudaFree(d_output_data_);
        d_output_data_ = nullptr;
    }
    if (d_output_size_) {
        cudaFree(d_output_size_);
        d_output_size_ = nullptr;
    }
    
    input_size_ = 0;
    initialized_ = false;
    parameters_copied_ = false;
}

bool neural_network_kernelKernel::checkCudaError(cudaError_t status, const std::string& context) {
    if (status != cudaSuccess) {
        last_error_ = context + ": " + cudaGetErrorString(status);
        RCLCPP_ERROR(rclcpp::get_logger("neural_network_kernelKernel"), 
                    "%s", last_error_.c_str());
        return false;
    }
    return true;
}

} // namespace robodsl
