#!/usr/bin/env python3
"""
Launch autonomous_vehicle_controller node

This file was auto-generated by RoboDSL.
"""

from launch import LaunchDescription
from launch_ros.actions import Node
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration

def generate_launch_description():
    # Declare launch arguments
    launch_arguments = [
        DeclareLaunchArgument(
            'use_sim_time',
            default_value='false',
            description='Use simulation time'
        ),
        DeclareLaunchArgument(
            'log_level',
            default_value='info',
            description='Log level for the node'
        ),
    ]
    
    # Create node
    autonomous_vehicle_controller_node = Node(
        package='robodsl_package',
        executable='autonomous_vehicle_controller_node',
        name='autonomous_vehicle_controller_node',
        namespace='/autonomous_vehicle_controller',
        output='screen',
        parameters=[
            {'control_frequency': 0.0},
            {'perception_frequency': 0.0},
            {'planning_frequency': 0.0},
            {'max_velocity': 0.0},
            {'max_acceleration': 0.0},
            {'safety_distance': 0.0},
            {'time_to_collision_threshold': 0.0},
            {'traffic_sign_detector_path': ""},
            {'lane_detector_path': ""},
            {'behavior_predictor_path': ""},
            {'use_sim_time': LaunchConfiguration("use_sim_time")},
        ],
        arguments=['--ros-args', '--log-level', LaunchConfiguration('log_level')],
    )

    return LaunchDescription(launch_arguments + [autonomous_vehicle_controller_node])
