// Generated by RoboDSL - DO NOT EDIT

#ifndef ROBOT_CPP_NODE_NODE_HPP
#define ROBOT_CPP_NODE_NODE_HPP

// Standard includes
#include <memory>
#include <string>
#include <vector>
#include <map>
#include <cmath>
#include <functional>
#include <thread>
#include <atomic>

// ROS2 includes
#include <rclcpp/rclcpp.hpp>

// Message includes
#include <std_msgs/msg/string.hpp>

// Additional ROS2 includes

// CUDA includes (if needed)

// OpenCV includes (if needed)

// Type definitions
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

// Forward declarations for custom types

// CUDA parameter structs

namespace robot_cpp {

class Robot_cpp_nodeNode : public rclcpp::Node {
public:
    explicit Robot_cpp_nodeNode(const rclcpp::NodeOptions& options = rclcpp::NodeOptions());
    virtual ~Robot_cpp_nodeNode();


    // Timer callbacks

    // Subscriber callbacks
    void on_cpp_input(const std_msgs::msg::String::ConstSharedPtr msg);

    // Service callbacks



    // User-defined C++ methods

private:
    // Publishers
    std::shared_ptr<rclcpp::Publisher<std_msgs::msg::String>> cpp_topic_pub_;

    // Subscribers
    rclcpp::Subscription<std_msgs::msg::String>::SharedPtr cpp_input_sub_;

    // Services


    // Timers

    // Lifecycle state tracking

    
    // Processing control
    bool enable_processing_{true};

    // Parameters
    int cpp_param_;

    // Latest message storage

    // CUDA kernel member variables

    // Helper methods
    void init_parameters();
    void init_publishers();
    void init_subscribers();
    void init_services();
    void init_timers();
};

} // namespace robot_cpp

#endif // ROBOT_CPP_NODE_NODE_HPP
