// Generated by RoboDSL - DO NOT EDIT


#include "cuda/occupancy_grid_update_kernel.cuh"
#include <algorithm>
#include <stdexcept>
#include <thrust/device_vector.h>
// NOTE: Thrust algorithms are used in this kernel.

// Define uchar type if not already defined
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

namespace robodsl {

namespace {

// Device kernel implementation
__global__ void occupancy_grid_update_kernel(
    float** filtered_points,    int* num_points,    float** grid_data,    int* grid_width,    int* grid_height,    float* resolution,    float** robot_pose,    float** updated_grid, int num_elements
) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    const int stride = blockDim.x * gridDim.x;

    // Process elements in parallel
    for (int i = idx; i < num_elements; i += stride) {
        // Kernel implementation here
        // Example: output[i] = process(input[i], parameters);
    }
}

} // anonymous namespace

occupancy_grid_updateKernel::occupancy_grid_updateKernel(cudaStream_t* stream)
    : stream_(stream) {
    // Initialize CUDA device if needed
    cudaError_t status = cudaGetDevice(&device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get CUDA device: ") + cudaGetErrorString(status);
        return;
    }
    
    // Get device properties
    cudaDeviceProp props;
    status = cudaGetDeviceProperties(&props, device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get device properties: ") + cudaGetErrorString(status);
        return;
    }
    
    // Calculate optimal block size based on device properties
    max_threads_per_block_ = props.maxThreadsPerBlock;
    max_blocks_per_dim_ = props.maxGridSize[0];
    
    // CUDA device initialized successfully
    // Device: %s (Compute %d.%d)
}

occupancy_grid_updateKernel::~occupancy_grid_updateKernel() {
    try {
        freeDeviceMemory();
    } catch (const std::exception& e) {
        // Error in destructor: %s
    }
}

bool occupancy_grid_updateKernel::initialize(const float** input, size_t input_size) {
    if (!input || input_size == 0) {
        last_error_ = "Input pointer is null or size is zero";
        return false;
    }
    
    // Free any previously allocated memory
    freeDeviceMemory();
    
    // Store input size
    input_size_ = input_size;
    
    // Allocate device memory
    if (!allocateDeviceMemory()) {
        return false;
    }
    
    // Declare status variable once
    cudaError_t status;
    
    // Copy input data to device
    status = cudaMemcpyAsync(
        d_filtered_points_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy filtered_points to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_num_points_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy num_points to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_grid_data_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy grid_data to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_grid_width_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy grid_width to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_grid_height_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy grid_height to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_resolution_, 
        input, 
        input_size_ * sizeof(float), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy resolution to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_robot_pose_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy robot_pose to device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after initialization")) {
        return false;
    }
    
    initialized_ = true;
    return true;
}

bool occupancy_grid_updateKernel::process(const float** parameters, size_t param_size, float** output, size_t output_size) {
    if (!initialized_) {
        return false;
    }
    
    if (!output || output_size < input_size_) {
        last_error_ = "Output buffer is null or too small";
        return false;
    }
    
    // Declare status variable for this method
    cudaError_t status;
    
    // Copy parameters to device if needed
    if (parameters && !parameters_copied_) {
        status = cudaMemcpyAsync(
            d_parameters_, 
            parameters, 
            param_size, 
            cudaMemcpyHostToDevice,
            stream_ ? *stream_ : 0
        );
        
        if (!checkCudaError(status, "Copy parameters to device")) {
            return false;
        }
        
        parameters_copied_ = true;
    }
    
    // Calculate grid and block dimensions
    int block_size = std::min(max_threads_per_block_, kBlockSize);
    int num_blocks = (input_size_ + block_size - 1) / block_size;
    num_blocks = std::min(num_blocks, max_blocks_per_dim_);
    
    // Launch kernel
    occupancy_grid_update_kernel<<<num_blocks, block_size, 0, stream_ ? *stream_ : 0>>>(
        d_filtered_points_,        d_num_points_,        d_grid_data_,        d_grid_width_,        d_grid_height_,        d_resolution_,        d_robot_pose_,        d_updated_grid_, input_size_
    );
    
    // Check for kernel launch errors
    status = cudaGetLastError();
    if (!checkCudaError(status, "Kernel launch")) {
        return false;
    }
    
    // Copy results back to host
    status = cudaMemcpyAsync(
        output, 
        d_updated_grid_, 
        input_size_ * sizeof(float*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy updated_grid from device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after processing")) {
        return false;
    }
    
    return true;
}

bool occupancy_grid_updateKernel::allocateDeviceMemory() {
    cudaError_t status;
    
    // Allocate memory for all parameters
    status = cudaMalloc(&d_filtered_points_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate filtered_points memory")) {
        // Free previously allocated memory
        return false;
    }
    status = cudaMalloc(&d_num_points_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate num_points memory")) {
        // Free previously allocated memory
        if (d_filtered_points_) {
            cudaFree(d_filtered_points_);
            d_filtered_points_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_grid_data_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate grid_data memory")) {
        // Free previously allocated memory
        if (d_filtered_points_) {
            cudaFree(d_filtered_points_);
            d_filtered_points_ = nullptr;
        }
        if (d_num_points_) {
            cudaFree(d_num_points_);
            d_num_points_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_grid_width_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate grid_width memory")) {
        // Free previously allocated memory
        if (d_filtered_points_) {
            cudaFree(d_filtered_points_);
            d_filtered_points_ = nullptr;
        }
        if (d_num_points_) {
            cudaFree(d_num_points_);
            d_num_points_ = nullptr;
        }
        if (d_grid_data_) {
            cudaFree(d_grid_data_);
            d_grid_data_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_grid_height_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate grid_height memory")) {
        // Free previously allocated memory
        if (d_filtered_points_) {
            cudaFree(d_filtered_points_);
            d_filtered_points_ = nullptr;
        }
        if (d_num_points_) {
            cudaFree(d_num_points_);
            d_num_points_ = nullptr;
        }
        if (d_grid_data_) {
            cudaFree(d_grid_data_);
            d_grid_data_ = nullptr;
        }
        if (d_grid_width_) {
            cudaFree(d_grid_width_);
            d_grid_width_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_resolution_, input_size_ * sizeof(float));
    if (!checkCudaError(status, "Allocate resolution memory")) {
        // Free previously allocated memory
        if (d_filtered_points_) {
            cudaFree(d_filtered_points_);
            d_filtered_points_ = nullptr;
        }
        if (d_num_points_) {
            cudaFree(d_num_points_);
            d_num_points_ = nullptr;
        }
        if (d_grid_data_) {
            cudaFree(d_grid_data_);
            d_grid_data_ = nullptr;
        }
        if (d_grid_width_) {
            cudaFree(d_grid_width_);
            d_grid_width_ = nullptr;
        }
        if (d_grid_height_) {
            cudaFree(d_grid_height_);
            d_grid_height_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_robot_pose_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate robot_pose memory")) {
        // Free previously allocated memory
        if (d_filtered_points_) {
            cudaFree(d_filtered_points_);
            d_filtered_points_ = nullptr;
        }
        if (d_num_points_) {
            cudaFree(d_num_points_);
            d_num_points_ = nullptr;
        }
        if (d_grid_data_) {
            cudaFree(d_grid_data_);
            d_grid_data_ = nullptr;
        }
        if (d_grid_width_) {
            cudaFree(d_grid_width_);
            d_grid_width_ = nullptr;
        }
        if (d_grid_height_) {
            cudaFree(d_grid_height_);
            d_grid_height_ = nullptr;
        }
        if (d_resolution_) {
            cudaFree(d_resolution_);
            d_resolution_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_updated_grid_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate updated_grid memory")) {
        // Free previously allocated memory
        if (d_filtered_points_) {
            cudaFree(d_filtered_points_);
            d_filtered_points_ = nullptr;
        }
        if (d_num_points_) {
            cudaFree(d_num_points_);
            d_num_points_ = nullptr;
        }
        if (d_grid_data_) {
            cudaFree(d_grid_data_);
            d_grid_data_ = nullptr;
        }
        if (d_grid_width_) {
            cudaFree(d_grid_width_);
            d_grid_width_ = nullptr;
        }
        if (d_grid_height_) {
            cudaFree(d_grid_height_);
            d_grid_height_ = nullptr;
        }
        if (d_resolution_) {
            cudaFree(d_resolution_);
            d_resolution_ = nullptr;
        }
        if (d_robot_pose_) {
            cudaFree(d_robot_pose_);
            d_robot_pose_ = nullptr;
        }
        return false;
    }
    
    return true;
}

void occupancy_grid_updateKernel::freeDeviceMemory() {
    if (d_filtered_points_) {
        cudaFree(d_filtered_points_);
        d_filtered_points_ = nullptr;
    }
    if (d_num_points_) {
        cudaFree(d_num_points_);
        d_num_points_ = nullptr;
    }
    if (d_grid_data_) {
        cudaFree(d_grid_data_);
        d_grid_data_ = nullptr;
    }
    if (d_grid_width_) {
        cudaFree(d_grid_width_);
        d_grid_width_ = nullptr;
    }
    if (d_grid_height_) {
        cudaFree(d_grid_height_);
        d_grid_height_ = nullptr;
    }
    if (d_resolution_) {
        cudaFree(d_resolution_);
        d_resolution_ = nullptr;
    }
    if (d_robot_pose_) {
        cudaFree(d_robot_pose_);
        d_robot_pose_ = nullptr;
    }
    if (d_updated_grid_) {
        cudaFree(d_updated_grid_);
        d_updated_grid_ = nullptr;
    }
    
    input_size_ = 0;
    initialized_ = false;
    parameters_copied_ = false;
}

bool occupancy_grid_updateKernel::checkCudaError(cudaError_t status, const std::string& context) {
    if (status != cudaSuccess) {
        last_error_ = context + ": " + cudaGetErrorString(status);
        return false;
    }
    return true;
}

} // namespace robodsl
