#!/usr/bin/env python3
"""
Launch camera_synchronizer node

This file was auto-generated by RoboDSL.
"""

from launch import LaunchDescription
from launch_ros.actions import Node
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration

def generate_launch_description():
    # Declare launch arguments
    launch_arguments = [
        DeclareLaunchArgument(
            'use_sim_time',
            default_value='false',
            description='Use simulation time'
        ),
        DeclareLaunchArgument(
            'log_level',
            default_value='info',
            description='Log level for the node'
        ),
    ]
    
    # Create node
    camera_synchronizer_node = Node(
        package='robodsl_package',
        executable='camera_synchronizer_node',
        name='camera_synchronizer_node',
        namespace='/camera_synchronizer',
        output='screen',
        parameters=[
            {'sync_tolerance': 0.0},
            {'max_queue_size': 0},
            {'use_sim_time': LaunchConfiguration("use_sim_time")},
        ],
        arguments=['--ros-args', '--log-level', LaunchConfiguration('log_level')],
    )

    return LaunchDescription(launch_arguments + [camera_synchronizer_node])
