#!/usr/bin/env python3
"""
Launch safety_node node

This file was auto-generated by RoboDSL.
"""

from launch import LaunchDescription
from launch_ros.actions import Node
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration

def generate_launch_description():
    # Declare launch arguments
    launch_arguments = [
        DeclareLaunchArgument(
            'use_sim_time',
            default_value='false',
            description='Use simulation time'
        ),
        DeclareLaunchArgument(
            'log_level',
            default_value='info',
            description='Log level for the node'
        ),
    ]
    
    # Create node
    safety_node_node = Node(
        package='robodsl_package',
        executable='safety_node_node',
        name='safety_node_node',
        namespace='/safety_node',
        output='screen',
        parameters=[
            {'max_acceleration': ""},
            {'emergency_stop_distance': ""},
            {'enable_emergency_stop': False},
            {'use_sim_time': LaunchConfiguration("use_sim_time")},
        ],
        arguments=['--ros-args', '--log-level', LaunchConfiguration('log_level')],
    )

    return LaunchDescription(launch_arguments + [safety_node_node])
