// Generated by RoboDSL - DO NOT EDIT


#ifndef COLLISION_DETECTION_KERNEL_HPP
#define COLLISION_DETECTION_KERNEL_HPP



#include <cuda_runtime.h>
#include <cstdint>
#include <string>

// Define uchar type if not already defined
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif



namespace robodsl {


/**
 * @brief CUDA kernel wrapper class for collision_detection
 * 
 * This class provides a C++ interface to CUDA kernels, handling memory management
 * and kernel launches. It's designed to work with the ROS2 node lifecycle.
 */
class collision_detectionKernel {
public:
    /**
     * @brief Construct a new collision_detection Kernel object
     * 
     * @param stream CUDA stream to use for kernel execution (nullptr for default stream)
     */
    explicit collision_detectionKernel(cudaStream_t* stream = nullptr);
    
    /**
     * @brief Destroy the collision_detection Kernel object
     * 
     * Frees all allocated device memory.
     */
    ~collision_detectionKernel();
    
    // Delete copy constructor and assignment operator
    collision_detectionKernel(const collision_detectionKernel&) = delete;
    collision_detectionKernel& operator=(const collision_detectionKernel&) = delete;
    
    /**
     * @brief Initialize the kernel with input data
     * 
     * @param input Input data to process
     * @return true if initialization was successful, false otherwise
     */
    // Initialize the kernel with input data (host pointer and size)
    bool initialize(const float** input, size_t input_size);
    
    /**
     * @brief Process the input data using the CUDA kernel
     * 
     * @param parameters Kernel parameters
     * @return std::vector<bool*> Processed output data
     */
    // Process the input data using the CUDA kernel (host pointer and size)
    bool process(const bool** parameters, size_t param_size, bool** output, size_t output_size);
    
    /**
     * @brief Get the last error message, if any
     * 
     * @return std::string The last error message, or an empty string if no error
     */
    const std::string& getLastError() const { return last_error_; }
    
    /**
     * @brief Check if the kernel was initialized successfully
     * 
     * @return true if initialized, false otherwise
     */
    bool isInitialized() const { return initialized_; }
    
private:
    // Device memory pointers
    float** d_robot_joints_ = nullptr;  //!< Device memory for robot_joints
    float** d_robot_geometry_ = nullptr;  //!< Device memory for robot_geometry
    float** d_obstacle_points_ = nullptr;  //!< Device memory for obstacle_points
    int* d_num_obstacles_ = nullptr;  //!< Device memory for num_obstacles
    bool** d_collision_detected_ = nullptr;  //!< Device memory for collision_detected

    // Kernel state and configuration
    size_t input_size_ = 0;                //!< Number of input elements
    int device_id_ = 0;                    //!< CUDA device ID
    int max_threads_per_block_ = 256;      //!< Max threads per block
    int max_blocks_per_dim_ = 65535;       //!< Max blocks per grid dimension


    // Parameter state (for kernels with parameters)
    bool parameters_copied_ = false;
    bool* last_parameters_{};
    bool** d_parameters_ = nullptr;

    cudaStream_t* stream_ = nullptr;  //!< CUDA stream for async operations
    bool initialized_ = false;        //!< Whether the kernel is properly initialized
    std::string last_error_;         //!< Last error message, if any
    
    // CUDA kernel launch configuration
    static constexpr int kBlockSize = 256;  //!< Threads per block
    
    /**
     * @brief Check for CUDA errors and update last_error_ if needed
     * 
     * @param status CUDA status to check
     * @param context Context string for error messages
     * @return true if no error, false otherwise
     */
    bool checkCudaError(cudaError_t status, const std::string& context);
    
    /**
     * @brief Allocate device memory
     * 
     * @return true if allocation was successful, false otherwise
     */
    bool allocateDeviceMemory();
    
    /**
     * @brief Free device memory
     */
    void freeDeviceMemory();
};

// Kernel function declaration (must be a free function, not a member function)
__global__ void collision_detection_kernel(    const float** d_robot_joints_,    const float** d_robot_geometry_,    const float** d_obstacle_points_,    const int* d_num_obstacles_,    const bool** d_collision_detected_,    int num_elements
);

} // namespace robodsl


#endif // COLLISION_DETECTION_KERNEL_HPP
