name: Build Debian Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          devscripts \
          debhelper \
          dh-python \
          build-essential \
          python3-all \
          python3-setuptools \
          python3-sphinx \
          python3-sphinx-rtd-theme \
          python3-sphinxcontrib.apidoc

    - name: Build the Debian package
      run: |
        dpkg-buildpackage -us -uc

    - name: Archive .deb files
      uses: actions/upload-artifact@v4
      with:
        name: debian-packages
        path: ../*.deb
