// Generated by RoboDSL - DO NOT EDIT


#include "cuda/feature_matching_kernel.cuh"
#include <algorithm>
#include <stdexcept>

// Define uchar type if not already defined
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

namespace robodsl {

namespace {

// Device kernel implementation
__global__ void feature_matching_kernel(
    float** image1,    float** image2,    int* width,    int* height,    float** keypoints1,    float** keypoints2,    int* num_keypoints,    float** matches,    int** num_matches, int num_elements
) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    const int stride = blockDim.x * gridDim.x;

    // Process elements in parallel
    for (int i = idx; i < num_elements; i += stride) {
        // Kernel implementation here
        // Example: output[i] = process(input[i], parameters);
    }
}

} // anonymous namespace

feature_matchingKernel::feature_matchingKernel(cudaStream_t* stream)
    : stream_(stream) {
    // Initialize CUDA device if needed
    cudaError_t status = cudaGetDevice(&device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get CUDA device: ") + cudaGetErrorString(status);
        return;
    }
    
    // Get device properties
    cudaDeviceProp props;
    status = cudaGetDeviceProperties(&props, device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get device properties: ") + cudaGetErrorString(status);
        return;
    }
    
    // Calculate optimal block size based on device properties
    max_threads_per_block_ = props.maxThreadsPerBlock;
    max_blocks_per_dim_ = props.maxGridSize[0];
    
    // CUDA device initialized successfully
    // Device: %s (Compute %d.%d)
}

feature_matchingKernel::~feature_matchingKernel() {
    try {
        freeDeviceMemory();
    } catch (const std::exception& e) {
        // Error in destructor: %s
    }
}

bool feature_matchingKernel::initialize(const float** input, size_t input_size) {
    if (!input || input_size == 0) {
        last_error_ = "Input pointer is null or size is zero";
        return false;
    }
    
    // Free any previously allocated memory
    freeDeviceMemory();
    
    // Store input size
    input_size_ = input_size;
    
    // Allocate device memory
    if (!allocateDeviceMemory()) {
        return false;
    }
    
    // Declare status variable once
    cudaError_t status;
    
    // Copy input data to device
    status = cudaMemcpyAsync(
        d_image1_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy image1 to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_image2_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy image2 to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_width_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy width to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_height_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy height to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_keypoints1_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy keypoints1 to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_keypoints2_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy keypoints2 to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_num_keypoints_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy num_keypoints to device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after initialization")) {
        return false;
    }
    
    initialized_ = true;
    return true;
}

bool feature_matchingKernel::process(const int** parameters, size_t param_size, float** output, size_t output_size) {
    if (!initialized_) {
        return false;
    }
    
    if (!output || output_size < input_size_) {
        last_error_ = "Output buffer is null or too small";
        return false;
    }
    
    // Declare status variable for this method
    cudaError_t status;
    
    // Copy parameters to device if needed
    if (parameters && !parameters_copied_) {
        status = cudaMemcpyAsync(
            d_parameters_, 
            parameters, 
            param_size, 
            cudaMemcpyHostToDevice,
            stream_ ? *stream_ : 0
        );
        
        if (!checkCudaError(status, "Copy parameters to device")) {
            return false;
        }
        
        parameters_copied_ = true;
    }
    
    // Calculate grid and block dimensions
    int block_size = std::min(max_threads_per_block_, kBlockSize);
    int num_blocks = (input_size_ + block_size - 1) / block_size;
    num_blocks = std::min(num_blocks, max_blocks_per_dim_);
    
    // Launch kernel
    feature_matching_kernel<<<num_blocks, block_size, 0, stream_ ? *stream_ : 0>>>(
        d_image1_,        d_image2_,        d_width_,        d_height_,        d_keypoints1_,        d_keypoints2_,        d_num_keypoints_,        d_matches_,        d_num_matches_, input_size_
    );
    
    // Check for kernel launch errors
    status = cudaGetLastError();
    if (!checkCudaError(status, "Kernel launch")) {
        return false;
    }
    
    // Copy results back to host
    status = cudaMemcpyAsync(
        output, 
        d_matches_, 
        input_size_ * sizeof(float*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy matches from device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        output, 
        d_num_matches_, 
        input_size_ * sizeof(int*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy num_matches from device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after processing")) {
        return false;
    }
    
    return true;
}

bool feature_matchingKernel::allocateDeviceMemory() {
    cudaError_t status;
    
    // Allocate memory for all parameters
    status = cudaMalloc(&d_image1_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate image1 memory")) {
        // Free previously allocated memory
        return false;
    }
    status = cudaMalloc(&d_image2_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate image2 memory")) {
        // Free previously allocated memory
        if (d_image1_) {
            cudaFree(d_image1_);
            d_image1_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_width_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate width memory")) {
        // Free previously allocated memory
        if (d_image1_) {
            cudaFree(d_image1_);
            d_image1_ = nullptr;
        }
        if (d_image2_) {
            cudaFree(d_image2_);
            d_image2_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_height_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate height memory")) {
        // Free previously allocated memory
        if (d_image1_) {
            cudaFree(d_image1_);
            d_image1_ = nullptr;
        }
        if (d_image2_) {
            cudaFree(d_image2_);
            d_image2_ = nullptr;
        }
        if (d_width_) {
            cudaFree(d_width_);
            d_width_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_keypoints1_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate keypoints1 memory")) {
        // Free previously allocated memory
        if (d_image1_) {
            cudaFree(d_image1_);
            d_image1_ = nullptr;
        }
        if (d_image2_) {
            cudaFree(d_image2_);
            d_image2_ = nullptr;
        }
        if (d_width_) {
            cudaFree(d_width_);
            d_width_ = nullptr;
        }
        if (d_height_) {
            cudaFree(d_height_);
            d_height_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_keypoints2_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate keypoints2 memory")) {
        // Free previously allocated memory
        if (d_image1_) {
            cudaFree(d_image1_);
            d_image1_ = nullptr;
        }
        if (d_image2_) {
            cudaFree(d_image2_);
            d_image2_ = nullptr;
        }
        if (d_width_) {
            cudaFree(d_width_);
            d_width_ = nullptr;
        }
        if (d_height_) {
            cudaFree(d_height_);
            d_height_ = nullptr;
        }
        if (d_keypoints1_) {
            cudaFree(d_keypoints1_);
            d_keypoints1_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_num_keypoints_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate num_keypoints memory")) {
        // Free previously allocated memory
        if (d_image1_) {
            cudaFree(d_image1_);
            d_image1_ = nullptr;
        }
        if (d_image2_) {
            cudaFree(d_image2_);
            d_image2_ = nullptr;
        }
        if (d_width_) {
            cudaFree(d_width_);
            d_width_ = nullptr;
        }
        if (d_height_) {
            cudaFree(d_height_);
            d_height_ = nullptr;
        }
        if (d_keypoints1_) {
            cudaFree(d_keypoints1_);
            d_keypoints1_ = nullptr;
        }
        if (d_keypoints2_) {
            cudaFree(d_keypoints2_);
            d_keypoints2_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_matches_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate matches memory")) {
        // Free previously allocated memory
        if (d_image1_) {
            cudaFree(d_image1_);
            d_image1_ = nullptr;
        }
        if (d_image2_) {
            cudaFree(d_image2_);
            d_image2_ = nullptr;
        }
        if (d_width_) {
            cudaFree(d_width_);
            d_width_ = nullptr;
        }
        if (d_height_) {
            cudaFree(d_height_);
            d_height_ = nullptr;
        }
        if (d_keypoints1_) {
            cudaFree(d_keypoints1_);
            d_keypoints1_ = nullptr;
        }
        if (d_keypoints2_) {
            cudaFree(d_keypoints2_);
            d_keypoints2_ = nullptr;
        }
        if (d_num_keypoints_) {
            cudaFree(d_num_keypoints_);
            d_num_keypoints_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_num_matches_, input_size_ * sizeof(int*));
    if (!checkCudaError(status, "Allocate num_matches memory")) {
        // Free previously allocated memory
        if (d_image1_) {
            cudaFree(d_image1_);
            d_image1_ = nullptr;
        }
        if (d_image2_) {
            cudaFree(d_image2_);
            d_image2_ = nullptr;
        }
        if (d_width_) {
            cudaFree(d_width_);
            d_width_ = nullptr;
        }
        if (d_height_) {
            cudaFree(d_height_);
            d_height_ = nullptr;
        }
        if (d_keypoints1_) {
            cudaFree(d_keypoints1_);
            d_keypoints1_ = nullptr;
        }
        if (d_keypoints2_) {
            cudaFree(d_keypoints2_);
            d_keypoints2_ = nullptr;
        }
        if (d_num_keypoints_) {
            cudaFree(d_num_keypoints_);
            d_num_keypoints_ = nullptr;
        }
        if (d_matches_) {
            cudaFree(d_matches_);
            d_matches_ = nullptr;
        }
        return false;
    }
    
    return true;
}

void feature_matchingKernel::freeDeviceMemory() {
    if (d_image1_) {
        cudaFree(d_image1_);
        d_image1_ = nullptr;
    }
    if (d_image2_) {
        cudaFree(d_image2_);
        d_image2_ = nullptr;
    }
    if (d_width_) {
        cudaFree(d_width_);
        d_width_ = nullptr;
    }
    if (d_height_) {
        cudaFree(d_height_);
        d_height_ = nullptr;
    }
    if (d_keypoints1_) {
        cudaFree(d_keypoints1_);
        d_keypoints1_ = nullptr;
    }
    if (d_keypoints2_) {
        cudaFree(d_keypoints2_);
        d_keypoints2_ = nullptr;
    }
    if (d_num_keypoints_) {
        cudaFree(d_num_keypoints_);
        d_num_keypoints_ = nullptr;
    }
    if (d_matches_) {
        cudaFree(d_matches_);
        d_matches_ = nullptr;
    }
    if (d_num_matches_) {
        cudaFree(d_num_matches_);
        d_num_matches_ = nullptr;
    }
    
    input_size_ = 0;
    initialized_ = false;
    parameters_copied_ = false;
}

bool feature_matchingKernel::checkCudaError(cudaError_t status, const std::string& context) {
    if (status != cudaSuccess) {
        last_error_ = context + ": " + cudaGetErrorString(status);
        return false;
    }
    return true;
}

} // namespace robodsl
