// Generated by RoboDSL - DO NOT EDIT


#include "cuda/gaussian_blur_kernel.cuh"
#include <algorithm>
#include <stdexcept>

// Define uchar type if not already defined
#ifndef __UCHAR_TYPE__
typedef unsigned char uchar;
#endif

namespace robodsl {

namespace {

// Device kernel implementation
__global__ void gaussian_blur_kernel(
    float** input_image,    int* width,    int* height,    int* channels,    float** blurred_image, int num_elements
) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    const int stride = blockDim.x * gridDim.x;

    // Process elements in parallel
    for (int i = idx; i < num_elements; i += stride) {
        // Kernel implementation here
        // Example: output[i] = process(input[i], parameters);
    }
}

} // anonymous namespace

gaussian_blurKernel::gaussian_blurKernel(cudaStream_t* stream)
    : stream_(stream) {
    // Initialize CUDA device if needed
    cudaError_t status = cudaGetDevice(&device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get CUDA device: ") + cudaGetErrorString(status);
        return;
    }
    
    // Get device properties
    cudaDeviceProp props;
    status = cudaGetDeviceProperties(&props, device_id_);
    if (status != cudaSuccess) {
        last_error_ = std::string("Failed to get device properties: ") + cudaGetErrorString(status);
        return;
    }
    
    // Calculate optimal block size based on device properties
    max_threads_per_block_ = props.maxThreadsPerBlock;
    max_blocks_per_dim_ = props.maxGridSize[0];
    
    // CUDA device initialized successfully
    // Device: %s (Compute %d.%d)
}

gaussian_blurKernel::~gaussian_blurKernel() {
    try {
        freeDeviceMemory();
    } catch (const std::exception& e) {
        // Error in destructor: %s
    }
}

bool gaussian_blurKernel::initialize(const float** input, size_t input_size) {
    if (!input || input_size == 0) {
        last_error_ = "Input pointer is null or size is zero";
        return false;
    }
    
    // Free any previously allocated memory
    freeDeviceMemory();
    
    // Store input size
    input_size_ = input_size;
    
    // Allocate device memory
    if (!allocateDeviceMemory()) {
        return false;
    }
    
    // Declare status variable once
    cudaError_t status;
    
    // Copy input data to device
    status = cudaMemcpyAsync(
        d_input_image_, 
        input, 
        input_size_ * sizeof(float*), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy input_image to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_width_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy width to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_height_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy height to device")) {
        return false;
    }
    status = cudaMemcpyAsync(
        d_channels_, 
        input, 
        input_size_ * sizeof(int), 
        cudaMemcpyHostToDevice,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy channels to device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after initialization")) {
        return false;
    }
    
    initialized_ = true;
    return true;
}

bool gaussian_blurKernel::process(const float** parameters, size_t param_size, float** output, size_t output_size) {
    if (!initialized_) {
        return false;
    }
    
    if (!output || output_size < input_size_) {
        last_error_ = "Output buffer is null or too small";
        return false;
    }
    
    // Declare status variable for this method
    cudaError_t status;
    
    // Copy parameters to device if needed
    if (parameters && !parameters_copied_) {
        status = cudaMemcpyAsync(
            d_parameters_, 
            parameters, 
            param_size, 
            cudaMemcpyHostToDevice,
            stream_ ? *stream_ : 0
        );
        
        if (!checkCudaError(status, "Copy parameters to device")) {
            return false;
        }
        
        parameters_copied_ = true;
    }
    
    // Calculate grid and block dimensions
    int block_size = std::min(max_threads_per_block_, kBlockSize);
    int num_blocks = (input_size_ + block_size - 1) / block_size;
    num_blocks = std::min(num_blocks, max_blocks_per_dim_);
    
    // Launch kernel
    gaussian_blur_kernel<<<num_blocks, block_size, 0, stream_ ? *stream_ : 0>>>(
        d_input_image_,        d_width_,        d_height_,        d_channels_,        d_blurred_image_, input_size_
    );
    
    // Check for kernel launch errors
    status = cudaGetLastError();
    if (!checkCudaError(status, "Kernel launch")) {
        return false;
    }
    
    // Copy results back to host
    status = cudaMemcpyAsync(
        output, 
        d_blurred_image_, 
        input_size_ * sizeof(float*), 
        cudaMemcpyDeviceToHost,
        stream_ ? *stream_ : 0
    );
    
    if (!checkCudaError(status, "Copy blurred_image from device")) {
        return false;
    }
    
    // Synchronize to ensure the copy is complete
    if (stream_) {
        status = cudaStreamSynchronize(*stream_);
    } else {
        status = cudaDeviceSynchronize();
    }
    
    if (!checkCudaError(status, "Synchronize after processing")) {
        return false;
    }
    
    return true;
}

bool gaussian_blurKernel::allocateDeviceMemory() {
    cudaError_t status;
    
    // Allocate memory for all parameters
    status = cudaMalloc(&d_input_image_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate input_image memory")) {
        // Free previously allocated memory
        return false;
    }
    status = cudaMalloc(&d_width_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate width memory")) {
        // Free previously allocated memory
        if (d_input_image_) {
            cudaFree(d_input_image_);
            d_input_image_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_height_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate height memory")) {
        // Free previously allocated memory
        if (d_input_image_) {
            cudaFree(d_input_image_);
            d_input_image_ = nullptr;
        }
        if (d_width_) {
            cudaFree(d_width_);
            d_width_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_channels_, input_size_ * sizeof(int));
    if (!checkCudaError(status, "Allocate channels memory")) {
        // Free previously allocated memory
        if (d_input_image_) {
            cudaFree(d_input_image_);
            d_input_image_ = nullptr;
        }
        if (d_width_) {
            cudaFree(d_width_);
            d_width_ = nullptr;
        }
        if (d_height_) {
            cudaFree(d_height_);
            d_height_ = nullptr;
        }
        return false;
    }
    status = cudaMalloc(&d_blurred_image_, input_size_ * sizeof(float*));
    if (!checkCudaError(status, "Allocate blurred_image memory")) {
        // Free previously allocated memory
        if (d_input_image_) {
            cudaFree(d_input_image_);
            d_input_image_ = nullptr;
        }
        if (d_width_) {
            cudaFree(d_width_);
            d_width_ = nullptr;
        }
        if (d_height_) {
            cudaFree(d_height_);
            d_height_ = nullptr;
        }
        if (d_channels_) {
            cudaFree(d_channels_);
            d_channels_ = nullptr;
        }
        return false;
    }
    
    return true;
}

void gaussian_blurKernel::freeDeviceMemory() {
    if (d_input_image_) {
        cudaFree(d_input_image_);
        d_input_image_ = nullptr;
    }
    if (d_width_) {
        cudaFree(d_width_);
        d_width_ = nullptr;
    }
    if (d_height_) {
        cudaFree(d_height_);
        d_height_ = nullptr;
    }
    if (d_channels_) {
        cudaFree(d_channels_);
        d_channels_ = nullptr;
    }
    if (d_blurred_image_) {
        cudaFree(d_blurred_image_);
        d_blurred_image_ = nullptr;
    }
    
    input_size_ = 0;
    initialized_ = false;
    parameters_copied_ = false;
}

bool gaussian_blurKernel::checkCudaError(cudaError_t status, const std::string& context) {
    if (status != cudaSuccess) {
        last_error_ = context + ": " + cudaGetErrorString(status);
        return false;
    }
    return true;
}

} // namespace robodsl
